kind: Pod
apiVersion: v1
metadata:
  name: nginx-nfs
  namespace: mock
spec:
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 128Mi
      name: nginx-nfs
      command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/azure/outfile; sleep 1; done
      volumeMounts:
        - name: disk01
          mountPath: /mnt/azure
  volumes:
    - name: disk01
      persistentVolumeClaim:
        claimName: pvc-nfs
