apiVersion: v1
kind: Service
metadata:
  name: node-red
  namespace: mock
  labels:
    app: node-red
spec:
  selector:
    app: node-red
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1880
  type: LoadBalancer
