apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: drupal:10.3.0-php8.3-fpm-alpine3.20
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
