apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  namespace: dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
        - name: init-drupal-code
          image: drupal:10.3.0-php8.3-fpm-alpine3.20
          command:
            - sh
            - -c
            - |
              if [ "$(find "/mnt/drupal" -mindepth 1 -print -quit)" ]; then
                  echo 'Directory not empty'
              else
                  echo 'Starting to copy drupal code'
                  cp -r /opt/drupal/web/* /mnt/drupal || true
                  cp /mnt/drupal/sites/default/default.settings.php /mnt/drupal/sites/default/settings.php || true
                  mkdir -p /mnt/drupal/sites/default/files || true            
                  chmod 766 /mnt/drupal/sites/default/files || true
                  chmod 666 /mnt/drupal/sites/default/settings.php || true
                  echo 'Finished copying drupal code'
              fi
          volumeMounts:
            - name: volume
              mountPath: /mnt/drupal
              readOnly: false
      containers:
        - name: drupal
          image: drupal:10.3.0-php8.3-fpm-alpine3.20
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: volume
              mountPath: /var/www/html
              readOnly: false
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azure-blob-storage
