apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  namespace: dev
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=3
  nfs:
    server: 10.227.224.4
    path: /aksvolume
