apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-ultra
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
