apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-storage
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azureblob-nfs-premium
  resources:
    requests:
      storage: 5Gi
