apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile
  resources:
    requests:
      storage: 100Gi
