apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi
