apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: dev
data:
  nginx.conf: |
    error_log /var/log/nginx/error.log debug;
    server {
        listen 80;
        server_name localhost;  

        root /var/www/html;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        rewrite ^/core/authorize.php/core/authorize.php(.*)$ /core/authorize.php$1;

        location ~ \.php$ {
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_pass drupal.dev.svc.cluster.local :9000;
        }

        location ~ /\.ht {
            deny all;
        }
        location = /favicon.ico {
            log_not_found off; access_log off;
        }

        location = /robots.txt {
            log_not_found off; access_log off; allow all;
        }
    }
