apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"
          image: nginx:1.17.4-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: volume
              readOnly: false
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: my-azurefile
        - name: nginx-conf
          configMap:
            name: nginx-conf
