apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-deployment-alert
  namespace: flux-config
spec:
  summary: "Flux Kustomization Alert"
  providerRef:
    name: webhook-provider
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
