apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-deployment-alert
  namespace: flux-config
spec:
  providerRef:
    name: webhook-provider
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
  summary: "Flux Kustomization Alert"
