apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red-deployment
  namespace: mock-2
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: nodered/node-red:latest
          # command: ["node-red", "-u", "/mnt/azure"]
          ports:
            - containerPort: 1880
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      #     volumeMounts:
      #       - name: disk01
      #         mountPath: /mnt/azure
      # volumes:
      #   - name: disk01
      #     persistentVolumeClaim:
      #       claimName: pvc-nfs-ultra
